export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const CITY_REQUEST = 'CITY_REQUEST';
export const CITY_SUCCESS = 'CITY_SUCCESS';
export const CITY_FAIL = 'CITY_FAIL';

export const FORECAST_REQUEST = 'FORECAST_REQUEST';
export const FORECAST_SUCCESS = 'FORECAST_SUCCESS';
export const FORECAST_FAIL = 'FORECAST_FAIL';

export const ADD_FAV_REQUEST = 'ADD_FAV_REQUEST';
export const ADD_FAV_SUCCESS = 'ADD_FAV_SUCCESS';
export const ADD_FAV_FAIL = 'ADD_FAV_FAIL';

export const REMOVE_FAV_REQUEST = 'REMOVE_FAV_REQUEST';
export const REMOVE_FAV_SUCCESS = 'REMOVE_FAV_SUCCESS';
export const REMOVE_FAV_FAIL = 'REMOVE_FAV_FAIL';

export const FAV_CITY_REQUEST = 'FAV_CITY_REQUEST';
export const FAV_CITY_SUCCESS = 'FAV_CITY_SUCCESS';
export const FAV_CITY_FAIL = 'FAV_CITY_FAIL';

export const GEO_REQUEST = 'GEO_REQUEST';
export const GEO_SUCCESS = 'GEO_SUCCESS';
export const GEO_FAIL = 'GEO_FAIL';

export const API = 'xfuX4MiN426mL9wcbUBwoChlh6qDLLG2';
